### ISSUE TITLE
Patched

### ISSUE THREAD

**Issue by cy-polo** [Y0GAAAA/Quiziniere-Corrupter#1]
Salut @Y0GAAAA,

je t’informes que ceci ne fonctionne plus depuis plusieurs mois.
Bonne soirée,
Polo

**Comment by Y0GAAAA** [comment]
Il semblerait en effet qu'ils aient rendus leur système plus robuste, merci de m'avoir informé Polo, je supprime la repo quand tu aura pris connaissance de mon message 😸

**Comment by cy-polo** [comment]
C'était vraiment marrant, mais il y a eu des abus, et ils ont corrigés ce soucis.
Mais il doit encore rester des choses rigolo a découvrir ✌
A bientot !
